체결 API를 작성한다
f-lab-edu/big-trader pull request #46
Opened 2022-12-27 16:31 UTC by sjhello

2022-12-28 01:52 UTC, f-lab-lyan requested changes
설정 파일들을 보면, 공통적으로
```
server:
  port: 8082
```
가 들어가 있는데 이 부분을 하나로 합칠 수는 없는 걸까요?

2022-12-28 01:52 UTC, f-lab-lyan commented on stock-exchange/build.gradle.kts
> +    testImplementation(testFixtures(project(":config:redis-config")))
plugin에서 `java-test-fixtures`를 축가하는 것과는 다른 효과 인가요?

2022-12-28 01:52 UTC, f-lab-lyan commented on stock-exchange/build.gradle.kts
> +    implementation("org.springframework.boot:spring-boot-starter-web")
단순히 카프카 컨슈머를 위한 컴포넌트라면, 이 디펜던시는 필요 없을 수도 있지 않을까요? :-)

2022-12-28 03:05 UTC, sjhello commented on stock-exchange/build.gradle.kts
> +    implementation("org.springframework.boot:spring-boot-starter-web")
네 현재 이 모듈이 웹과 관련된 기능을 하는 것은 아니기 때문에 디펜던시를 삭제하는게 좋을 것 같습니다.

2022-12-28 03:05 UTC, sjhello commented on stock-exchange/build.gradle.kts
> +    testImplementation(testFixtures(project(":config:redis-config")))
플러그인 적용만으로 test 의존성을 주입할 수 없어서 넣어두었습니다.

지금은 테스트 코드가 없는데요... 나중에 테스트 코드 상에서 카프카, 레디스 설정에 대한 testFixutures 의존성이 필요할 수 도 있겠어서 일단은 넣어 두었습니다.

2022-12-28 03:07 UTC, sjhello commented on stock-exchange/build.gradle.kts
> +    implementation("org.springframework.boot:spring-boot-starter-web")
> 설정 파일들을 보면, 공통적으로
> 
> ```
> server:
>   port: 8082
> ```
> 
> 가 들어가 있는데 이 부분을 하나로 합칠 수는 없는 걸까요?

boot-starter-web 의존성을 삭제하여서 이 부분은 삭제하여도 괜찮을 것 같습니다.

2022-12-28 03:07 UTC, sjhello commented
> 설정 파일들을 보면, 공통적으로
> 
> ```
> server:
>   port: 8082
> ```
> 
> 가 들어가 있는데 이 부분을 하나로 합칠 수는 없는 걸까요?

boot-starter-web 의존성을 삭제하여서 이 부분은 삭제하여도 괜찮을 것 같습니다.

2023-01-02 14:38 UTC, f-lab-lyan approved these changes

2023-01-02 14:39 UTC, merged