feat: Dummy App Push api 개발
f-lab-edu/big-trader pull request #6
Opened 2022-09-25 10:43 UTC by sjhello

2022-09-25 12:23 UTC, hungrytech requested changes

2022-09-25 12:23 UTC, hungrytech commented on app-push-api/src/main/kotlin/com/flab/bigtrader/apppush/presentation/AppPushController.java
> +    }
App push는 어떠한 앱 메시지를 전달한다고 생각하는데 GET 메서드가 아니라 POST 메서드여야 하지 않을까요? 🤔

2022-09-25 12:49 UTC, sjhello commented on app-push-api/src/main/kotlin/com/flab/bigtrader/apppush/presentation/AppPushController.java
> +    }
app-push에 어떤 요청이 있을때 그 요청에 대한 메시지를 전달해준다고 생각해서 GET으로 정의했었습니다. 이때 저는 상태코드 자체를 REST API에서 말하는 리소스로 보지 않았네요.

추가로 FCM REST API 에서는 message send를 어떤 http method를 사용하고 있는지 조사해봤더니 POST를 사용하고 있었습니다.
아마도 메시지 자체를 리소스로 보고있지 않나 싶습니다.

수정해서 다시 pr 올리겠습니다.  
참고: [FCM REST API](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages/send)

2022-09-25 13:11 UTC, hungrytech commented
추후에 요청 body랑 Response 공통명세를 정하면 좋겠습니다. 😄

2022-09-25 13:13 UTC, hungrytech commented on app-push-api/src/main/kotlin/com/flab/bigtrader/apppush/presentation/AppPushController.java
> +    }
dummyApi 이름도 변경해주셨으면 좋겠어요 😂

2022-09-25 13:20 UTC, sjhello commented on app-push-api/src/main/kotlin/com/flab/bigtrader/apppush/presentation/AppPushController.java
> +    }
ㅎㅎ 지금보니 테스트토 바꾸지 않았네요 같이 올리겠습니다~

2022-09-25 13:28 UTC, hungrytech approved these changes

2022-09-25 13:28 UTC, merged

2022-09-28 14:34 UTC, f-lab-lyan commented on app-push-api/src/main/kotlin/com/flab/bigtrader/apppush/presentation/AppPushController.java
> +
```suggestion
    // TODO: 나중에 구현체 추가
```